# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: publish on pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/xspf-lib
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python and PDM
      uses: pdm-project/setup-pdm@v2
      with:
        cache: true
    - name: Build
      run: |
        pdm build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
