name: Lint and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM with
        uses: pdm-project/setup-pdm@v3
        with:
          cache: true
      - name: Install dependencies
        run: |
          pdm sync -dG lint --no-default
      - name: Test
        run: |
          pdm run lint

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up PDM with Python ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
    - name: Install dependencies
      run: |
        pdm sync -dG test --no-default
    - name: Test
      run: |
        pdm run test
